DROP TABLE IF EXISTS Warenkorb;
DROP TABLE IF EXISTS Historie;
DROP TABLE IF EXISTS Freunde;
DROP TABLE IF EXISTS Produktliste;
DROP TABLE IF EXISTS ProjektUser;

DROP TABLE IF EXISTS Projekte;
DROP TABLE IF EXISTS Benutzer;
DROP TABLE IF EXISTS Produkte;
